name: 3dml
channels:
  - conda-forge
  - pytorch
dependencies:
  - ipyvolume=0.5.2
  - ipywidgets=7.5.0
  - numpy-stl=2.10.1
  - voila=0.1.20
  - voila-material
  - pandas=1.3
  - scikit-learn=0.24
  - sympy=1.8
  - plotly=5.1
  - gdown
  - pytorch >= 1.9.0
  - scikit-learn
  - jupyterlab_widgets
  - shortuuid